// web/src/App.vue
<template>
  <div v-if="isLoading" id="app">
    <main class="loading" role="status" aria-busy="true" aria-live="polite">
      <div class="loading-spinner" aria-hidden="true"></div>
      <p>Checking authentication...</p>
    </main>
  </div>
  <div v-else id="app">
    <RouterView />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { RouterView } from 'vue-router'
import { useAuth } from './composables/useAuth'

const { isLoading, checkAuthentication } = useAuth()

onMounted(() => {
  checkAuthentication()
})
</script>

<style scoped>
#app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.loading {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1rem;
}

.loading p {
  color: var(--color-text-muted);
  font-size: 0.875rem;
}

.loading-spinner {
  width: 2.5rem;
  height: 2.5rem;
  border: 3px solid var(--color-border);
  border-top-color: var(--color-accent);
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// web/src/App.svelte
<script lang="ts">
  let currentYear = new Date().getFullYear();
</script>

<main>
  <section class="hero">
    <div class="hero-content">
      <h1>Datamonster</h1>
      <p class="tagline">Homelab Data Platform</p>
    </div>

    <div class="status">
      <span class="status-dot"></span>
      <span class="status-text">System Online</span>
    </div>
  </section>

  <footer>
    <p>&copy; {currentYear} Datamonster</p>
  </footer>
</main>

<style>
  main {
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  .hero {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 2rem;
    gap: 3rem;
  }

  .hero-content {
    text-align: center;
  }

  h1 {
    margin: 0;
    font-size: clamp(2.5rem, 8vw, 4.5rem);
    font-weight: 700;
    background: linear-gradient(135deg, var(--color-accent) 0%, #a78bfa 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  .tagline {
    margin: 0.75rem 0 0;
    font-size: 1.25rem;
    color: var(--color-text-muted);
    letter-spacing: 0.02em;
  }

  .status {
    display: flex;
    align-items: center;
    gap: 0.625rem;
    padding: 0.75rem 1.5rem;
    background: var(--color-bg-elevated);
    border: 1px solid var(--color-border);
    border-radius: 9999px;
  }

  .status-dot {
    width: 0.5rem;
    height: 0.5rem;
    background: var(--color-success);
    border-radius: 50%;
    box-shadow: 0 0 8px var(--color-success);
    animation: pulse 2s ease-in-out infinite;
  }

  .status-text {
    font-size: 0.875rem;
    color: var(--color-text-muted);
  }

  @keyframes pulse {
    0%,
    100% {
      opacity: 1;
    }
    50% {
      opacity: 0.5;
    }
  }

  footer {
    padding: 1.5rem;
    text-align: center;
    border-top: 1px solid var(--color-border);
  }

  footer p {
    margin: 0;
    font-size: 0.875rem;
    color: var(--color-text-muted);
  }
</style>
